name: DEPLOY_PRODUCTION

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Start Build
        env:
          GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL }}
        run: yarn build

      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir public
