name: DEPLOY_STAGING

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Start Build
        env:
          GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL_STAGING }}
        run: yarn build:staging

      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir public
