name: Deploy Staging

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn

      - name: Build Gatsby
        run: yarn build:staging
        # env:
        #   GATSBY_SITE_URL: ${{ secrets.GATSBY_SITE_URL_STAGING }}

      # - name: Download Build Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: gatsby-build-staging
      #     # path: public

      # - name: Display structure of downloaded files
      #   run: ls -R

      # - name: Deploy to Netlify
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod --dir public
